trigger: none

variables:
  - group: Build Variables

resources:
  repositories:
    - repository: template
      type: git
      name: WindowsProtocolTestSuites/WindowsProtocolTestSuites
      ref: AzurePipelines-main


pool:
  vmImage: windows-2022

jobs:
- job:
  displayName: DotNetCore Build
  workspace:
    clean: false
  timeoutInMinutes: 0
  steps:
  - checkout: self
  - task: UseDotNet@2
    displayName: Use .NET Core sdk 8.x
    inputs:
      version: '8.x'
  - task: NuGetAuthenticate@1
    inputs:
      feedUrl: 'https://microsoft.pkgs.visualstudio.com/WindowsProtocolTestSuites/_packaging/windowsprotocoltestsuites_PublicPackages/nuget/v3/index.json'
  - task: npmAuthenticate@0
    inputs:
      workingFile: '/ProtocolTestManager/PTMService/PTMService/ClientApp/.npmrc'
  - task: PowerShell@2
    displayName: Build
    inputs:
      targetType: filePath
      filePath: './$(build.solutionFolder)/build.ps1'
      arguments: '-Configuration $(build.configuration) -OutDir $(Build.ArtifactStagingDirectory)/staging'

  - task: ArchiveFiles@2
    displayName: 'Archive $(Build.ArtifactStagingDirectory)/staging'
    inputs:
      rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/staging'
      includeRootFolder: false
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(build.archiveName).zip'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(build.archiveName).zip'
    condition: succeededOrFailed()
#  - template: pipelines/build/DotNetCore-PTMCli-Build-steps.yml@template