trigger: none

variables:
  - group: Build Variables

resources:
  repositories:
    - repository: template
      type: git
      name: WindowsProtocolTestSuites/WindowsProtocolTestSuites
      ref: AzurePipelines-main


pool:
  vmImage: windows-2022

jobs:
- job:
  displayName: DotNetCore Build
  workspace:
    clean: false
  timeoutInMinutes: 0
  steps:
  - task: NuGetAuthenticate@1
    inputs:
      feedUrl: 'https://microsoft.pkgs.visualstudio.com/WindowsProtocolTestSuites/_packaging/windowsprotocoltestsuites_PublicPackages/nuget/v3/index.json'
  - task: npmAuthenticate@0
    inputs:
      workingFile: 'PTMService/ClientApp/.npmrc'
  - template: pipelines/build/DotNetCore-PTMCli-Build-steps.yml@template