trigger: none
variables:
- group: Build Variables
resources:
  repositories:
  - repository: template
    type: git
    name: WindowsProtocolTestSuites/WindowsProtocolTestSuites
    ref: AzurePipelines-main
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: Azure-Pipelines-1ESPT-ExDShared
      image: windows-2022
      os: windows
    customBuildTags:
    - ES365AIMigrationTooling
    stages:
    - stage: stage
      jobs:
      - job: ''
        displayName: DotNetCore Build
        workspace:
          clean: false
        timeoutInMinutes: 0
        steps:
        - task: NuGetAuthenticate@1
          inputs:
            feedUrl: 'https://microsoft.pkgs.visualstudio.com/WindowsProtocolTestSuites/_packaging/windowsprotocoltestsuites_PublicPackages/nuget/v3/index.json'
            nuGetServiceConnections: 'windowsprotocoltestsuites_PublicPackages'
        - template: pipelines/build/1es/DotNetCore-PTMCli-Build-steps.yml@template